spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: aliyun
    password: 886887
    url: jdbc:mysql://39.106.37.93/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: create
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 39.106.37.93
    port: 6379
    password: 886887
server:
  context-path: /sell
  port: 8080
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  mpAppId: wxb777e31c3c710246
  mpAppSecret: 50fbd4f9a32b9c3d10c7a4697e5d5c18
  openAppId: wxb777e31c3c710246
  openAppSecret: 50fbd4f9a32b9c3d10c7a4697e5d5c18
  mchId: 1393357702
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://jackson.s1.natapp.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://jackson.s1.natapp.cc
  wechatOpenAuthorize: http://jackson.s1.natapp.cc
  sell: http://jackson.s1.natapp.cc
